cluster_name: harrydevbox
 
azure_cluster:
  harrydevbox:
    infra_node_num: 1 
    infra_vm_size : Standard_D3_v2
    worker_node_num: 2
    worker_vm_size: Standard_D3_v2
    azure_location: westus
 
UserGroups:
  DLWSAdmins:
    Allowed: [ "jinl@microsoft.com", "jinlmsft@hotmail.com", "t-lezhan@microsoft.com" ]
    uid : "20000"
    gid : "20001"
  DLWSRegister:
    Allowed: [ "@gmail.com" ]
    uid : "20001-29999"
    gid : "20001"
 
WebUIregisterGroups: [ "DLWSRegister"]
WebUIauthorizedGroups: [ "DLWSAdmins" ]
WebUIadminGroups: ["DLWSAdmins"]
 
DeployAuthentications : ["Corp", "Gmail", "Live"]
 
WinbindServers: []   
 
webuiport: 3080
